name: CI

on:
  push:
    branches:
      - master
  pull_request:

# Should discard previous running build on same branch
concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # == CHECK == #
  check:
    name: "Check beta stable and MSRV=1.64.0"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchains:
          - 1.64.0
          - stable
          - beta
        cargo-locked: ["--locked", ""]
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-toolchains }}
          override: true

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Update `Cargo.lock`
        if: matrix.cargo-locked != '--locked'
        run: rm Cargo.lock

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: ${{ matrix.cargo-locked }}

  # == BUILD & TEST == #
  build-and-test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    needs: [check]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-toolchains:
          - 1.64.0
          - stable
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          override: true
          toolchain: ${{ matrix.rust-toolchains }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Cargo test (no raw identifier)
        if: matrix.rust-toolchains == '1..0'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.cargo-locked }}

      - name: Cargo test (all)
        if: matrix.rust-toolchains != '1.64.0'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.cargo-locked }} --features better-docs
